# Generated by Django 6.0.6 on 2026-06-18 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('format_prompt', 'Строка формата (text)'), ('max_context_size', 'Максимальная величина контекста (int)'), ('gpt_type', 'Тип использующейся модели GPT'), ('openai_key', 'API ключ OpenAI'), ('yandex_catalog_id', 'ID каталога Yandex Cloud'), ('yandex_api_key', 'API ключ Yandex Cloud')], max_length=30)),
                ('property_value_text', models.TextField(blank=True, null=True)),
                ('property_value_int', models.IntegerField(blank=True, null=True)),
                ('property_value_bool', models.IntegerField(default=False)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenAIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved_at', models.DateTimeField()),
                ('input', models.TextField()),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(default='', max_length=512)),
                ('content', models.TextField(default='')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActionContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated', models.DateTimeField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.action')),
            ],
        ),
        migrations.CreateModel(
            name='AssistantFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('user_prompt', models.TextField(default='')),
                ('system_prompt', models.TextField()),
                ('send_context', models.BooleanField(default=True)),
                ('send_to_llm_instantly', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('send_project_info', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated', models.DateTimeField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.data')),
            ],
        ),
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=128, verbose_name='Название')),
                ('content', models.TextField(default='', verbose_name='Формулировка гипотезы')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалена?')),
                ('linked_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hypothesis', verbose_name='Связана с')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project', verbose_name='Проект')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='hypothesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hypothesis'),
        ),
        migrations.CreateModel(
            name='ChatWithAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(default='Новый чат', max_length=32)),
                ('context_length', models.IntegerField(default=0)),
                ('closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.assistantfunction')),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hypothesis')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='hypothesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hypothesis'),
        ),
        migrations.CreateModel(
            name='HypothesisChangesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inprogress', 'Формируется'), ('ready', 'Сформирован')], max_length=12)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('summary_date', models.DateTimeField()),
                ('use_general_summary', models.BooleanField(default=False)),
                ('use_content_summary', models.BooleanField(default=False)),
                ('hypothesis_content_before', models.TextField(blank=True, null=True)),
                ('hypothesis_content_after', models.TextField(blank=True, null=True)),
                ('summary_hypothesis', models.TextField(blank=True, null=True)),
                ('summary_actions', models.TextField(blank=True, null=True)),
                ('summary_data', models.TextField(blank=True, null=True)),
                ('summary_insights', models.TextField(blank=True, null=True)),
                ('summary_metrics', models.TextField(blank=True, null=True)),
                ('summary_general', models.TextField(blank=True, null=True)),
                ('points_hypothesis', models.IntegerField(blank=True, default=0, null=True)),
                ('points_actions', models.IntegerField(blank=True, default=0, null=True)),
                ('points_data', models.IntegerField(blank=True, default=0, null=True)),
                ('points_insights', models.IntegerField(blank=True, default=0, null=True)),
                ('points_metrics', models.IntegerField(blank=True, default=0, null=True)),
                ('points_general', models.IntegerField(blank=True, default=0, null=True)),
                ('changes', models.IntegerField(default=0)),
                ('is_subordinate', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hypothesis')),
            ],
        ),
        migrations.CreateModel(
            name='DataChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_before', models.TextField(blank=True, null=True)),
                ('content_after', models.TextField(blank=True, null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.data')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hypothesischangessummary')),
            ],
        ),
        migrations.CreateModel(
            name='ActionChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_before', models.TextField(blank=True, null=True)),
                ('content_after', models.TextField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.action')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hypothesischangessummary')),
            ],
        ),
        migrations.CreateModel(
            name='HypothesisContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated', models.DateTimeField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hypothesis')),
            ],
        ),
        migrations.CreateModel(
            name='HypothesisMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('metric_type', models.CharField(choices=[('boolean', 'Чекбокс'), ('integer', 'Целое число'), ('float', 'Дробное число')], max_length=7)),
                ('deleted', models.BooleanField(default=False)),
                ('target_value', models.FloatField(default=0)),
                ('description', models.CharField(default='', max_length=128)),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hypothesis')),
            ],
        ),
        migrations.CreateModel(
            name='HypothesisMetricValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hypothesismetric')),
            ],
        ),
        migrations.CreateModel(
            name='HypothesisStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('changed', 'Изменена'), ('declined', 'Отклонена'), ('accepted', 'Принята'), ('inprogress', 'В работе'), ('deffered', 'Отложена')], max_length=20)),
                ('changing_time', models.DateTimeField()),
                ('deffered_to', models.DateTimeField(blank=True, default=None, null=True)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('changing_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_hypothesis', to='api.hypothesis')),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hypothesis')),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('deleted', models.BooleanField(default=False)),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hypothesis')),
            ],
        ),
        migrations.CreateModel(
            name='InsightChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_before', models.TextField(blank=True, null=True)),
                ('content_after', models.TextField(blank=True, null=True)),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.insight')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hypothesischangessummary')),
            ],
        ),
        migrations.CreateModel(
            name='InsightContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated', models.DateTimeField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.insight')),
            ],
        ),
        migrations.CreateModel(
            name='MetricChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_before', models.FloatField(blank=True, null=True)),
                ('value_after', models.FloatField(blank=True, null=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hypothesismetric')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hypothesischangessummary')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectChangesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inprogress', 'Формируется'), ('ready', 'Сформирован')], max_length=12)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('summary_date', models.DateTimeField()),
                ('use_general_summary', models.BooleanField(default=False)),
                ('use_content_summary', models.BooleanField(default=False)),
                ('changes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.AddField(
            model_name='hypothesischangessummary',
            name='subordinate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.projectchangessummary'),
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('owner', 'Owner')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestToAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=16)),
                ('message', models.TextField()),
                ('recieved_at', models.DateTimeField()),
                ('message_type', models.CharField(blank=True, choices=[('context', 'Контекст'), ('instruction', 'Инструкция'), ('user', 'Сообщение пользователя'), ('devprompt', 'Сообщение с форматом ответа')], max_length=12, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chatwithassistant')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('supervisor', 'Supervisor'), ('inactive', 'Inactive')], max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField()),
                ('action_type', models.CharField(choices=[('create', 'Создание'), ('delete', 'Удаление'), ('update', 'Изменение')], max_length=20)),
                ('hypothesis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hypothesis')),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hypothesismetric')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(help_text='Название настройки.', max_length=32)),
                ('value', models.CharField(help_text='Значение настройки.', max_length=32)),
                ('user', models.ForeignKey(help_text='Пользователь, к которому относится настройка.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройка пользователя',
                'verbose_name_plural': 'Настройки пользователей',
                'constraints': [models.UniqueConstraint(fields=('user', 'setting'), name='unique_user_setting')],
            },
        ),
    ]
